### PR TITLE
Adds compatibility blocks

### PR DESCRIPTION
**Pull request by MarkElf**
Adds a few missing blocks against my list.

### CODE REVIEW

**Review by CaptainObvious0 — CHANGES_REQUESTED** [review]
Good catch. I was able to confirm some of these, but others I was unable to confirm.

More specifically: Stairs, Trap_Doors, Blue_Ice, hopper, end_portal_frame, and weighted pressure plates. 
SeaGrass and Tall_SeaGrass were hard coded in, I'll try adding flags to these blocks. Iron_Bars are already added in, unless you're suggesting that the flags should be changed. If you could clarify these, I'll add them into the DefaultConfig.

If you haven't already, some notes about each flag can be found within the BlockProperties class (Starting at line 651) https://github.com/CaptainObvious0/NoCheatPlus/blob/ec5fb766a7952dd695b19d671d3240da7a563dcf/NCPCore/src/main/java/fr/neatmonster/nocheatplus/utilities/map/BlockProperties.java#L651
Although adding ground_height and ign_passable will fix most of these blocks, more specific block flags could be better.

**Comment by MarkElf** [comment]
I remember testing against early 1.13 support builds so not all the blocks were there at the time hence why you may find some additional blocks that aren't fully necessary. I was also messing around with the reflect setting quite a bit but leaving it as default seemed to work best. 

Iron bars and panes flagged passable when against a single block and attempting to walk into the pane or iron bar. The easiest way to replicate what I'm trying to referance is a block staircase with either panes or bars. That may be something to look further into. I.e

O=dirt block
L=pane/bar
X=Player 
OL
OOL   X
OOOLX

I agree that proper flags for some blocks like ender portal frames would work better though it's not something I'd be able to currently find much time for with my current classes. It took @SpacePupeh and I about an hour to peice together values that worked for farmland. My own testing found flags like thin_fence, which is meant for panes or bars, to be a bit buggy while ign_passable served as a quick and easy fix. I felt that getting the list out there was the least I could do to contribute with my time and inability to code. I'll revise what I can with my limited free time if someone else doesn't beat me to it.

**Comment by CaptainObvious0** [comment]
Makes sense. It seems all block shape models have been added, I'm just not sure where along the line these models are failing to apply. [Bukkit Models](https://github.com/CaptainObvious0/NoCheatPlus/tree/master/NCPCompatBukkit/src/main/java/fr/neatmonster/nocheatplus/compat/bukkit/model)

I still was not able to replicate the issue. I also just noticed the flags you are suggesting are the same ones already added. Maybe the issue was already fixed?

I can clearly find all the flags and the blocks that they are applied to, I just can't find where the block flags are used and properties are applied to them. The methods and code expand across so many different classes its hard to nail down where everything is. Finding the class would be a lot more useful than referring to the notes left in the code, that way, I could identify exactly what each flag is doing. 

I came into this project with little to no experience with Java, but over time I've learned bits and pieces. I'm mostly using trial and error and google to help me figure things out.

I'll adjust the flags/blocks and apply them in the future. Thanks for your help.

**Comment by MarkElf** [comment]
Notes:
Iron bars were missing from your list anyway.
Stairs work, so that's removed.
Walking under trapdoors still flags passable (Not explored proper flags) (try F_ATTACHED_LOW2_SNEW?)
Keeping flower pot
Keeping enchanting table
Keeping blue ice (try making long path of blue ice, takes a bit to trigger setback)
Seagrass has been fixed (assume tall too)
Regular (living) coral is okay, dead coral is undefined so leaving in. Unable to spawn coral walls, I assume they need to be defined too.
Repeaters do cause setback, leaving in
Hoppers seem okay
Pressure plates seem okay
Can't retest cocoa

**Comment by CaptainObvious0** [comment]
Iron bars can be found on lines 762/759
Still was unable to confirm trap doors. Possibly a video could help. Unless you are referencing Issue #11 
Still unable to confirm blue_ice - 55 blocks
Was able to confirm cocoa, so you can keep that.
Everything else has been confirmed/fixed.

Make sure you are not running and protocol hacks (ProtocolSupport) as it messes somewhat with the blocks.

**Comment by MarkElf** [comment]
Jumped around a bit on a small patch of blue ice then began sprint jumping down the path, may be related to issue #11
Blue ice: https://giphy.com/gifs/LpVZdfmGrCCmvYkaVW

Self-explanatory, I only see the ign_passable flag working at the moment but I didn't exactly explore all the options too hard. ( F_ATTACHED_LOW2_SNEW / F_FACING_LOW3D2_NSWE + default didn't work)
Trap doors: https://giphy.com/gifs/2xPPpONCWZgTATQ6QL

I'm leaving things as it is currently. Even using protocol support, blocks should work fine with NCP as it's safe to assume that server owners will be using compatibility plugins. I was using viaversion / backwards on 1.13.2 paperspigot when testing. 

It may be worth posting updates in the release section for testing on github.

**Comment by CaptainObvious0** [comment]
Seems fair enough. It’s most likely that ProtocolSupport is the source of some of these issues, as they may change block margins or have unexpected consequences.

Thanks for your help.

**Pull request merged**
