### PR TITLE
Some fixes and additions.

### PR DESCRIPTION
**Pull request by Lysandr0**
- Fix attempt for: [#563](https://github.com/NoCheatPlus/Issues/issues/563) (Seems to be working with no issues for now... :p)
- Allow the "SprintBack" subcheck to work, regardless the "AssumeSprint" workaround (+ fix a fp)
- Added tags for the Angle check (You can check what detection method is causing troubles and raise its corresponding threshold this way :p)
- Added tags for the InventoryMove check.

All commits seem to be okay through my testings. But since I actually lack the knownledge needed on how to properly code, I'd double check everything, just to be sure... :p

### CODE REVIEW

**Comment by CaptainObvious0** [comment]
Everything looks good except for InventoryMove. Are there any problems with using the hotbar while in survival mode? It was added to allow using middle click to select blocks while in creative, not sure if that applys to survival mode.

**Comment by Lysandr0** [comment]
If I recall correctly, you should be able to swap items in Survival from your inventory to your hotbar by middle clicking, but I could be wrong...

Will check this as soon as possible.

_Edit:_ In 1.13 (Survival) I can indeed swap items by middle clicking blocks, however, it doesn't seem to generate any false positive, so the skip hotbar check is not needed.

**Comment by CaptainObvious0** [comment]
Everything is good, but I do ask one change to the format to help keep things more clean. The tags should be added separately, and does not need repeated if statement for each cancel part.

A little example:
```
if (player.isSneaking) {
tags.add("isSneaking");
}
if (player.isSwimming) {
tags.add("isSwimming");
}

if (player.isSwmming | player.isSneaking) {
// cancel here
}
```
This way changes to the check can be done to one part, rather than changing each section with the same thing.

**Comment by Lysandr0** [comment]
Should be good now (hopefully :p)

**Comment by CaptainObvious0** [comment]
Thanks for your help :)

**Pull request merged**
